spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: dyk160513140.
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.kun: info
  file:
    name: log/blog-pro.blog

server:
  port: 8081